DROP TABLE CUSTOMERS CASCADE CONSTRAINTS
DROP TABLE KYC CASCADE CONSTRAINTS
DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS
DROP TABLE EMPLOYEE_PAY CASCADE CONSTRAINTS
DROP TABLE ACCOUNTS CASCADE CONSTRAINTS
DROP TABLE ACCOUNT_STRUCT CASCADE CONSTRAINTS
DROP TABLE CUSTOMER_ADDRESS CASCADE CONSTRAINTS
DROP TABLE EMPLOYEE_INFO CASCADE CONSTRAINTS